"""2023-09-03_16-00

Revision ID: 041c22788e76
Revises: 201ab0f728fe
Create Date: 2023-09-03 16:00:34.176085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041c22788e76'
down_revision = '201ab0f728fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_token', sa.String(length=128), nullable=True))
    op.drop_column('user', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'auth_token')
    # ### end Alembic commands ###
