"""2023-08-23_22-33

Revision ID: 201ab0f728fe
Revises: c4beaca111a5
Create Date: 2023-08-23 22:33:49.716743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201ab0f728fe'
down_revision = 'c4beaca111a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=128)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
