"""2023-08-19_21-57

Revision ID: 4e978bb5618c
Revises: 
Create Date: 2023-08-19 21:57:42.870431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e978bb5618c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('scout_id', sa.Integer(), nullable=False),
    sa.Column('totem', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('scout_group', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scout_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('trilho', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('validated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scout_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress')
    op.drop_table('user')
    # ### end Alembic commands ###
