"""2023-08-19_19-08

Revision ID: 57a643be40e3
Revises: f60e673bd619
Create Date: 2023-08-19 19:08:16.758506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a643be40e3'
down_revision = 'f60e673bd619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('scout_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('totem', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('scout_group', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('section', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('team', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=128), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_username_key', 'user', ['username'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('user', 'role')
    op.drop_column('user', 'team')
    op.drop_column('user', 'section')
    op.drop_column('user', 'scout_group')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'totem')
    op.drop_column('user', 'scout_id')
    # ### end Alembic commands ###
