"""2023-08-19_22-13

Revision ID: c4beaca111a5
Revises: 4e978bb5618c
Create Date: 2023-08-19 22:13:40.272764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4beaca111a5'
down_revision = '4e978bb5618c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_super_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_super_admin')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
