version: '3.8'

services:
  web:
    build: 
      dockerfile: Dockerfile.prod
    volumes:
      - ./services/web/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.prod
  db:
    volumes:
      - sleev_postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/nginx/:/usr/src/app/
    ports:
      - 1337:80

volumes:
  sleev_postgres_data_prod: