version: '3.8'

services:
  web:
    build: 
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/web:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.dev
  db:
    volumes:
      - sleev_postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  nginx:
    build: ./services/nginx
    volumes:
      - ./services/nginx/:/usr/src/app/
    ports:
      - 1338:80

volumes:
  app_data:
  sleev_postgres_data_dev: